version: '3.2'
services:
################################################################################
# Web Client
################################################################################
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "4200:4200"
    volumes:
      - .:/save-my-tabs
    environment:
      - API_URL=http://localhost:3000
    depends_on:
      - api
################################################################################
# Records Database
################################################################################
  db:
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/potgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pgdev
################################################################################
# Service API
################################################################################
  api:
    build:
      context: ./dev-api-server
      dockerfile: Dockerfile
    command: bin/dev
    volumes:
      - ./dev-api-server:/save-my-tabs
      - type: tmpfs
        target: /save-my-tabs/tmp/pids
    ports:
      - "3000:3000"
    depends_on:
      - db
